name: beyond_horizons
description: "Beyond Horizons - An airline management simulation game built with Flutter"
publish_to: 'none' # Private project, not for pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Assets (images, fonts, etc.) can be added here when needed
  assets:
    - assets/data/

  # Custom fonts can be added here
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: assets/fonts/CustomFont-Regular.ttf
